branches:
  only:
    - /^v(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-((?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$/
language: cpp
sudo: required
dist: bionic
compiler:
  - clang
matrix:
  include:
    - os: osx
      compiler: clang
      osx_image: xcode9.4
      env: BUILD_TYPE="Release"
env:
  global:
    - STATIC_ASSET_FILE_NAME="cfdgo-${TRAVIS_TAG}-${TRAVIS_OS_NAME}-${TRAVIS_OSX_IMAGE}_x86_64-static"
    - DYNAMIC_ASSET_FILE_NAME="cfdgo-${TRAVIS_TAG}-${TRAVIS_OS_NAME}-${TRAVIS_OSX_IMAGE}_x86_64"

addons:
  homebrew:
    packages:
      - cmake
    update: true

before_install:

install:
  - echo "cmake version check"
  - cmake --version

after_install:

before_script:
  - cd "${TRAVIS_BUILD_DIR}"
  - echo "${TRAVIS_BUILD_DIR}"
  - mkdir dist_static
  - mkdir dist_dynamic

script:
  - mkdir build
  - cmake -S . -B build
  - cmake -DCMAKE_BUILD_TYPE="$BUILD_TYPE" -DENABLE_SHARED=off -DENABLE_TESTS=off -DENABLE_JS_WRAPPER=off -DENABLE_CAPI=on --build build
  - cmake --build build
  - cd build
  - make install DESTDIR=../dist_static
  - cd ..
  - rm -rf build
  - mkdir build
  - cmake -S . -B build
  - cmake -DCMAKE_BUILD_TYPE="$BUILD_TYPE" -DENABLE_SHARED=on -DENABLE_TESTS=off -DENABLE_JS_WRAPPER=off -DENABLE_CAPI=on -DTARGET_RPATH="/usr/local/lib;@executable_path;./build/Release" --build build
  - cmake --build build
  - cd build
  - make install DESTDIR=../dist_dynamic
  - cd ..

after_success:
  - cd dist_static
  - ls -l usr/local/lib
  - zip -r "../${STATIC_ASSET_FILE_NAME}.zip" usr
  - cd ..
  - cd dist_dynamic
  - ls -l usr/local/lib
  - zip -r "../${DYNAMIC_ASSET_FILE_NAME}.zip" usr
  - cd ..

before_deploy:

deploy:
  provider: releases
  api_key: ${GITHUB_API_KEY}
  file:
    - "${STATIC_ASSET_FILE_NAME}.zip"
    - "${DYNAMIC_ASSET_FILE_NAME}.zip"
  draft: false
  prerelease: true
  on:
    tags: true
  skip_cleanup: true

after_deploy:

after_script: